# node scripts/gen-nav.js 'content/docs/TOC.md' 'data/docs_toc.json' '/docs/'
node scripts/gen-nav.js 'content/docs/dev/TOC.md' 'data/docs_dev_toc.json' '/docs/dev/'
node scripts/gen-nav.js 'content/docs/v3.0/TOC.md' 'data/docs_v30_toc.json' '/docs/v3.0/'
node scripts/gen-nav.js 'content/docs/v2.1/TOC.md' 'data/docs_v21_toc.json' '/docs/v2.1/'
# node scripts/gen-nav.js 'content/docs/v2.0/TOC.md' 'data/docs_v20_toc.json' '/docs/v2.0/'
# node scripts/gen-nav.js 'content/docs/v1.0/TOC.md' 'data/docs_v10_toc.json' '/docs/v1.0/'
node scripts/gen-nav.js 'content/docs-cn/TOC.md' 'data/docs_cn_toc.json' '/docs-cn/'
node scripts/gen-nav.js 'content/about-cn/recruit/TOC.md' 'data/recruit_cn_toc.json' '/about-cn/recruit/'